# Step 1: Base Image
FROM python:3.12-slim

# Step 2: Set working directory
WORKDIR /app

# Step 3: Copy files
COPY requirements.txt .

# Step 4: Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Step 5: Copy project files
COPY . .

# Step 6: Expose port
EXPOSE 8000

# Step 7: Run Django app
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

